### ISSUE TITLE
Unified dependency error

### ISSUE THREAD

**Issue by pottiera** [wataru-chocola/remark-extended-table#130]
Steps to reproduce: `npm i remark-extended-table` 

Error: `npm WARN Could not resolve dependency:
npm WARN peer unified@"^11.1.0" from remark-extended-table@2.0.0
npm WARN node_modules/remark-extended-table
npm WARN   remark-extended-table@"^2.0.0" from the root project
...
npm ERR! notarget No matching version found for unified@^11.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

Suggestion: put unified 11.0.4 as a dependency (because unified 11.1.0 doesn't exit)

**Comment by wataru-chocola** [comment]
Fixed at v2.0.1.

Thanks for reporting!
