### ISSUE TITLE
colspan more than 2 is not working

### ISSUE THREAD

**Issue by gutenye** [wataru-chocola/remark-extended-table#64]
Example

```
| a | b | c | 
| - | - | - |
| > | > | 1 |
```

Result

```
<td colspan="2">1</td>
```

Expect

```
<td colspan="3">1</td>
```

**Comment by wataru-chocola** [comment]
I've released a new version to fix this.

https://github.com/wataru-chocola/remark-extended-table/releases/tag/remark-extended-table%401.0.1

Could you try it?

Thanks.

**Comment by gutenye** [comment]
Fixed, thanks
