### ISSUE TITLE
How can i get this to work with mdsvex in a Sveltekit project?

### ISSUE THREAD

**Issue by flintec-studio** [wataru-chocola/remark-extended-table#84]
Hey there,

I've got a Sveltekit project that uses mdsvex to process the markdown files. (mdsvex supports all rehype and remark plugins.)
https://mdsvex.pngwn.io/docs#remarkplugins--rehypeplugins

1. Installing with pnpm flags up missing peer dependencies. Do all of these packages need to also be installed alongside your package?

![image](https://user-images.githubusercontent.com/102214117/224287746-1140d3aa-5788-4704-bed3-56c35e8296e4.png)

2. To use plugins i add them to the svelte.config.js file. Below is an example of the config file with rehypeSlug and rehypeAutolinkHeadings plugins (both working).
 
![image](https://user-images.githubusercontent.com/102214117/224288577-94a07de1-e679-42c4-a1a4-4862f34038e4.png)

3. Should this package work if i simply add it to my config? Thus far, I cant get it to work.

![image](https://user-images.githubusercontent.com/102214117/224288908-ef665d68-0eaf-433c-831b-acdf949c63fd.png)

Any help appreciated, thanks!
Alex

**Comment by wataru-chocola** [comment]
@flintec-studio 

> Do all of these packages need to also be installed alongside your package?

My packages are designed to be used with `remark/mdast/micromark-gfm-*` and `unified`. Usually, you won't need to install all of them manually. If your platform claims to support remark / rehype plugins, this generally means that core packages like `unified`, `remark-parse`, and `micromark` are already installed with it.

However, as I observe mdsvex's dependencies, they appear to utilize older versions of the unified / remark packages, which are not compatible with my plugin.

https://github.com/pngwn/MDsveX/blob/master/packages/mdsvex/package.json

> Should this package work if i simply add it to my config?

Without unified-related compatibility issue, I don't think my plugin works with mdsvex.
My plugin needs to add `handlers`  in `remark-rehype` plugin, but they don't have API for it.


Regards
